name: nucleo-f767zi build
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.9.1
        with:
          release: 13.2.Rel1
      - name: Build All (nucleo-f767zi)
        run: make PLATFORM=nucleo-f767zi -j2
